//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataAccessEntities : DbContext
    {
        public DataAccessEntities()
            : base("name=DataAccessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<l_admin> l_admin { get; set; }
        public DbSet<l_kategori> l_kategori { get; set; }
        public DbSet<l_uyeler> l_uyeler { get; set; }
        public DbSet<l_urunler> l_urunler { get; set; }
    }
}
