//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class l_admin
    {
        public int adm_id { get; set; }
        public string adm_name { get; set; }
        public string adm_kullanici_adi { get; set; }
        public string adm_sifre { get; set; }
        public bool adm_ispassive { get; set; }
    }
}
