//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class l_uyeler
    {
        public int uye_id { get; set; }
        public string uye_ad_soyad { get; set; }
        public string uye_kullanici_adi { get; set; }
        public string uye_sifre { get; set; }
        public string uye_foto_url { get; set; }
        public string uye_detay { get; set; }
        public Nullable<System.DateTime> uye_kayit_tarihi { get; set; }
        public string uye_telefon { get; set; }
        public string uye_mail { get; set; }
        public bool uye_ispassive { get; set; }
    }
}
